augment_input_features: true
augment_output_features: true
batch_size: 4
commitment_cost: 0.25
data_root: ./
decay: 0.0
decoder_type: wavenet
embedding_dim: 64
export_one_hot_features: true
features_path: features
filter_size: 3
gate_channels: 768
global_condition_dim: 128
input_dim: 256
input_features_dim: 47
input_features_filters: 13
input_features_type: mfcc
jitter_probability: 0.1
learning_rate: 0.0002
length: 7680
local_condition_dim: 768
n_layers: 20
n_loop: 2
normalize: true
normalizer_path: ../data/ibm/ibm-mfcc-stats.pickle
num_embeddings: 50
num_epochs: 1000
num_hiddens: 768
num_residual_layers: 2
num_workers: 1
output_features_dim: 47
output_features_filters: 13
output_features_type: mfcc
output_type: audio
quantize: 256
record_codebook_stats: false
record_gradient_stats: false
res_type: kaiser_fast
residual_channels: 768
sampling_rate: 16000
save_path: ./speech_output
skip_out_channels: 256
start_epoch: 0
top_db: 20
train_val_split: 0.8
trainer_type: wavenet
use_cuda: true
use_data_parallel: false
use_device: cuda:0
use_jitter: true
use_kaiming_normal: false
verbose: false
wavenet_type: WaveNet
